spring.application.name=back

# Database Configuration
spring.datasource.url=jdbc:mariadb://mariadb-store-cc/db_crustaceo-cascarudo_store?createDatabaseIfNotExist=true
spring.datasource.username=cc-store
spring.datasource.password=cc-store
