spring.application.name=back

# Database Configuration
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:3306/${DB_NAME:db_default}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}

# Bank API Configuration
bank.api.url=${BANK_API_URL:https://api-bank-class.ishimi.es}
bank.api.key=${BANK_API_KEY:gurt}
bank.store.recipient-iban=${BANK_STORE_IBAN:ES6600987654321098765432}
